# RuboCop configuration for React on Rails demos
# Based on Rails Omakase with adjustments for React on Rails

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"

# Rails Omakase style preferences
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Layout preferences
Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics adjustments for demo apps
Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "test/**/*"
    - "config/routes.rb"
    - "config/environments/*"

Metrics/ClassLength:
  Max: 200

# Rails specific
Rails/ApplicationRecord:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: false

# Performance
Performance/RedundantMerge:
  Enabled: true

# React on Rails specific patterns
Rails/OutputSafety:
  Exclude:
    - "app/helpers/react_on_rails_helper.rb"