# Inherit from Rails Omakase style
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Demo-specific adjustments
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
